### PR TITLE
Allow leaving username and password empty

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by kgorman** [comment]
I dunno, seems like we shouldn't encourage horrible practices @benmccann. I put in the auth foo, and I thought about making it optional, but decided not to.  Is there a specific use case where auth isn't appropriate?

**Comment by benmccann** [comment]
I wouldn't run in production without auth. But for benchmarking I just wanted to bring up a throw away machine on a segregated network. Having to setup up auth seems to be overkill for that use case. We could print a warning saying you should make sure the machine is on a properly firewalled network or something if you want

**Comment by kgorman** [comment]
good point. ;-)

**Comment by benmccann** [comment]
@tmcallaghan I've rebased this PR so that it can be merged. I think the change to `run.simple.bash` is a nice enhancement to the one you just merged

**Comment by benmccann** [comment]
@tmcallaghan thanks for the merge of my other PR. i've rebased this one again so that it's mergable again

**Comment by benmccann** [comment]
thanks!!

**Pull request merged**
