### PR TITLE
Need to use mongo-java-driver 2.13.0 to be able to test against MongoDB 3.0

### PR DESCRIPTION
**Pull request by benmccann**

### CODE REVIEW

**Comment by kgorman** [comment]
Also requires changes to the classes to support the new MongoCredential(). createMongoCRCredential is deprecated and needs to be replaced with createCredential in both *execute.java and *load.java.

**Comment by benmccann** [comment]
Ok, I've fixed the deprecation warnings

**Comment by benmccann** [comment]
@tmcallaghan would you be able to merge this? thanks!

**Comment by benmccann** [comment]
@tmcallaghan i've rebased this PR so that it can be merged

**Pull request merged**
